package com.guntzergames.medievalwipeout.enums;

public enum Phase {

	BEFORE_CREATOR_RESOURCE_DRAW, DURING_CREATOR_RESOURCE_DRAW, AFTER_CREATOR_RESOURCE_DRAW,
	BEFORE_CREATOR_DECK_DRAW, DURING_CREATOR_DECK_DRAW, AFTER_CREATOR_DECK_DRAW,
	BEFORE_CREATOR_PLAY, DURING_CREATOR_PLAY, AFTER_CREATOR_PLAY,
	BEFORE_JOINER_RESOURCE_DRAW, DURING_JOINER_RESOURCE_DRAW, AFTER_JOINER_RESOURCE_DRAW,
	BEFORE_JOINER_DECK_DRAW, DURING_JOINER_DECK_DRAW, AFTER_JOINER_DECK_DRAW,
	BEFORE_JOINER_PLAY, DURING_JOINER_PLAY, AFTER_JOINER_PLAY;  
	
}