package com.guntzergames.medievalwipeout.enums;

public enum Phase {
/*
	BEFORE_CREATOR_RESOURCE_CHOOSE, DURING_CREATOR_RESOURCE_CHOOSE, AFTER_CREATOR_RESOURCE_CHOOSE,
	BEFORE_CREATOR_RESOURCE_SELECT, DURING_CREATOR_RESOURCE_SELECT, AFTER_CREATOR_RESOURCE_SELECT,
	BEFORE_CREATOR_DECK_DRAW, DURING_CREATOR_DECK_DRAW, AFTER_CREATOR_DECK_DRAW,
	BEFORE_CREATOR_PLAY, DURING_CREATOR_PLAY, AFTER_CREATOR_PLAY,
	BEFORE_JOINER_RESOURCE_CHOOSE, DURING_JOINER_RESOURCE_CHOOSE, AFTER_JOINER_RESOURCE_CHOOSE,
	BEFORE_JOINER_RESOURCE_SELECT, DURING_JOINER_RESOURCE_SELECT, AFTER_JOINER_RESOURCE_SELECT,
	BEFORE_JOINER_DECK_DRAW, DURING_JOINER_DECK_DRAW, AFTER_JOINER_DECK_DRAW,
	BEFORE_JOINER_PLAY, DURING_JOINER_PLAY, AFTER_JOINER_PLAY;  
*/

	BEFORE_RESOURCE_CHOOSE, DURING_RESOURCE_CHOOSE, AFTER_RESOURCE_CHOOSE,
	BEFORE_RESOURCE_SELECT, DURING_RESOURCE_SELECT, AFTER_RESOURCE_SELECT,
	BEFORE_DECK_DRAW, DURING_DECK_DRAW, AFTER_DECK_DRAW,
	BEFORE_PLAY, DURING_PLAY, AFTER_PLAY;

}